### ISSUE TITLE
Variance for stats.py - 2nd data set is wrong 

### ISSUE THREAD

**Issue by mithi** [ColinShaw/cpp-extended-kalman-filters#2]
I think it's because the lists are initialized outside the `compute` function, making them global variables. So when the next variance is computed it still contains the elements from the previous data set. 

This can easily be solved by moving the initial empty lists inside the `compute` function: IE:
instead of:

```
pxs, pys, vxs, vys, rhos, phis, rhodots = [], [], [], [], [], [], []

def compute(filename):
    with open(filename, 'rt') as csvfile:
    /** ... **/
```
change it to:

```
def compute(filename):
    pxs, pys, vxs, vys, rhos, phis, rhodots = [], [], [], [], [], [], []
    with open(filename, 'rt') as csvfile:
    /** ... **/
```

**Comment by ColinShaw** [comment]
Thank you for noticing that, Mithi.  It used to only compute it on one file and I neglected to update that with multiple files.  It isn't scoped right for printing if it is in the compute function, but is if it is in the filename iterator.

**Comment by mithi** [comment]
Oh yeah @ColinShaw you're right about that sorry for not noticing or testing my pull request!
